### ISSUE TITLE
Support for adding personalized usernames

### ISSUE THREAD

**Issue by pydanny** [cartwheelweb/django-la-facebook#1]
Right now fb-% is the username created. This is pretty sucky. Proposed solutions:
1. A LaFacebookProfile could have a custom save that when inherited into a Profile would add a username field which would save the suggested username to the User object. I think once filled in, the Profile.username field would stop being editable via users. This touches on multiple inheritance and super class bits and is my preferred solution.
2. Another callback could support prompting the user for a custom username via a standard django form (meh).

**Comment by ptone** [comment]
Another option (in addition to, not instead of) would be to support the FB registration iFrame - which can be set up to collect additional fields.  Can also be used to handle non-fb based registrations.

http://developers.facebook.com/docs/plugins/registration/

**Comment by pydanny** [comment]
Thats an awesome idea for registration! Make them do the work! :D

**Comment by ptone** [comment]
Changed the user creation to capture name and email

The following changes were made:

just the facebook user ID is used in the association object
    for the identifier
The django user name is set to a slugified version of the fb:name
value, and the email is captured if available

To keep the email up to date, it is checked each time the user logs in with facebook

closed by 59fd8ccf14600dea138f39dd9f054977279aa1dd
closed by 59fd8ccf14600dea138f39dd9f054977279aa1dd
