### ISSUE TITLE
Remove subclass of oauth.Client for LinkedIn

### ISSUE THREAD

**Issue by ptone** [cartwheelweb/django-la-facebook#17]
in la_facebook.access is a subclass of oauth.Client used for LinkedIn Oauth.

This is used only in the OAuthAccess.make_api_call - in a way that I've verified is not executed in our current test setup.  Suggest that the else block be replaced by raising an exception if not isinstance(token, OAuth20Token).

**Comment by pydanny** [comment]
I'm leery of putting in other OAUTH implementations of something called django-la-facebook. I think a better idea would be to create a new project called django-la-linkedin. :)

**Comment by ptone** [comment]
right - the suggestion here is to pull it out ;-)
it came over from the parent project

**Comment by pydanny** [comment]
Lets pull it out!

**Comment by ptone** [comment]
pulled in 34123fb2089768a1343197b8842f92a5203bd605
