### ISSUE TITLE
KeyError "expires" when using "offline_access" permission

### ISSUE THREAD

**Issue by tuxcanfly** [cartwheelweb/django-la-facebook#28]
> Traceback:
> File "/home/giftopera/go_venv/src/django/django/core/handlers/base.py" in get_response
> 1.                         response = callback(request, _callback_args, *_callback_kwargs)
>    File "/home/giftopera/go-app/code/giftopera/la_facebook/views.py" in facebook_callback
> 2.         auth_token = access.check_token(unauth_token, request.GET)
>    File "/home/giftopera/go-app/code/giftopera/la_facebook/access.py" in check_token
> 3.                     int(response["expires"][-1])

Exception Type: KeyError at /facebook/callback
Exception Value: 'expires'

Maybe we need to handle this case and send expires=None?

**Comment by ptone** [comment]
don&#39;t assume response has an expires element

in facebook, if provider scope includes offline, 
token never expires

closed by 9390584a641e77234f6c5391c1dab20489f65e50
