### ISSUE TITLE
Please add "display=popup" option

### ISSUE THREAD

**Issue by bjornlilja** [cartwheelweb/django-la-facebook#29]
Hi

We are implementing your great application on our site. However, we wish to open the Facebook auth flow in a seprate popup window. There is a display option that can be passed to the authorize url. You are passing the default which causes the Facebook layout to not adapt to the window size gracefully.

This can be solved by passing display=popup to the auth url. Can you add this as an extra option to the la_facebook_login view?

Thanks

**Comment by ptone** [comment]
add some docs on using popup display layout

closed by 84d3fe2cc75a6e433ef9e37776600a43a4009c1d

**Comment by bjornlilja** [comment]
Thank you!!

**Comment by ptone** [comment]
You're welcome, please let us know if additional tweaks are needed.
