### ISSUE TITLE
callbacks package missing from setup.py

### ISSUE THREAD

**Issue by EmilStenstrom** [cartwheelweb/django-la-facebook#30]
I just tried installing la_facebook via pip directly from source. Seems the callbacks package is missing, and the simple reason for that seems to be that it's not in setup.py

**Comment by ptone** [comment]
I'm wondering if by callbacks you mean the oauth2 package?

-Preston

**Comment by EmilStenstrom** [comment]
I mean this directory: https://github.com/cartwheelweb/django-la-facebook/tree/master/la_facebook/callbacks

templatetags and utils are included in setup.py, not callbacks.

**Comment by ptone** [comment]
changed the way packages are included in setup.py

closed by 9be2b51da749f9dfb6ad7f7d3ecb70b4e1c0a1b7

**Comment by EmilStenstrom** [comment]
Thanks! :)
